language: scala
scala:
  - 2.10.4
  - 2.11.1
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email:
    - matthew@farwell.co.uk
before_install:
  - pip install --user codecov
after_success:
  - codecov
